### ISSUE TITLE
Segfault "n something"

### ISSUE THREAD

**Issue by aksr** [phonologus/qed-new#2] opened 2024-11-16 20:45 UTC
1. `qed <filename>`
2. Then execute inside *qed*: `n  something`
3. **Segmentation fault**

**Comment by phonologus** [comment] 2024-11-17 00:39
Yes, I can reproduce that. Will look into it.

**Comment by phonologus** [comment] 2024-11-17 18:00
Having said I can reproduce it, I did a fresh recompile, and now I can't reproduce it! Both my macOS and Linux rebuilds from a fresh git checkout don't segfault. Just weird.

Now, Qed throws a `?s` error after the buffer listing generated by `n`, because it tries to parse `something` as a substitute command (which would more canonically look like `s/mething`, which Qed interprets exactly as `s/mething//`). The substitution fails (unless the last line in your file matches `/mething/`), and Qed reports `?s`, All as expected.

Can you try a fresh rebuild, and see if you still get a segfault? And if you do still get a segfault, maybe it's a property of the contents of the file you are loading? I was just loading up local C files like `address.c`

**Comment by aksr** [comment] 2024-11-18 07:19
Strange, here, too — the same thing. I don't like this, it makes `qed` not stable enough. Do you use it regularly?

**Comment by phonologus** [comment] 2024-11-18 09:17
I use it as my default system editor (`EDITOR=qed`) for things like git/fossil commit messages. Otherwise I use the Heirloom `ex-vi` for manual editing, and `sed` and `awk` for text munging. I definitely would not rely on `qed-new` in its current state (or my older `qed`) for processing anything of significance.

However, I don't believe updating the memory model is too hard (in principle), but finding the time is not easy. (Actually, as a project to learn Rust, a `qed-rs` port would be perfect.... !).

**Comment by aksr** [comment] 2024-11-18 09:22
Still, don't let this C implementation die — you did most of the work already.

**Comment by phonologus** [comment] 2024-11-18 09:37
I'm only dipping my toes in Rust for fun, and I like a lot of the ideas, but I find the whole object/method syntax utterly foreign! My native language is C.

If you agree, I'll close this issue, as I think it is likely a manifestation of Issue #1, which I am leaving open and currently working on.

**Closed as completed** 2024-11-18 11:20 UTC
